[package]
name = "hot-reload-server"
description = "Hot reloading HTTP server for HTML, CSS, JavaScript and WebAssembly web development."
license = "ISC"
readme = "README.md"
repository = "https://github.com/ctsrc/hot-reload-server"
version = "0.0.0"
authors = ["Erik Nordstrøm <erik@nordstroem.no>"]
categories = ["web-programming::http-server", "development-tools", "filesystem"]
keywords = ["autoreload", "html5", "css3", "js", "wasm"]
edition = "2018"

[dependencies]
bytes = "1"
clap = { version = "4", features = ["cargo", "derive"] }
fsevent = "2"
futures-util = "0.3"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
